WIP responsiveness
BausCode/wmo_map pull request #1
Opened 2017-04-05 22:13 UTC by adamclark64

2017-04-06 22:38 UTC, gtwalford requested changes

2017-04-06 22:38 UTC, gtwalford commented on css/style.css
> +  /* margin: 142px 0px 0px 278px; */
let's just remove these

2017-04-06 22:38 UTC, gtwalford commented on js/input.js
> +        // .style("height","2vw")
I think we can just delete this

2017-04-06 22:38 UTC, gtwalford commented on js/map.js
> +      	.style("fill", "url(#linear-gradient)");
fix indentation

2017-04-07 17:19 UTC, adamclark64 commented on js/map.js
> +      	.style("fill", "url(#linear-gradient)");
idk why this looks like this in the diff but its good

2017-04-07 17:22 UTC, adamclark64 commented on css/style.css
> +  /* margin: 142px 0px 0px 278px; */
e26c87e

2017-04-07 17:35 UTC, gtwalford approved these changes

2017-04-07 17:35 UTC, merged